const fakeData = {
    "头痛": [
        {"idx": 1,
         "type": "input",
         "question": "请选择以下症状出现的时长",
         "answer": "__天",
         "ret": 'int',
         "summary": "头痛%s天"
         },
        {"idx": 2,
         "type": "choice",
         "question": "请问以下哪种情况下出现头痛",
         "answer": ['受凉', '过度劳累', '活动', '感冒', '睡眠', '不明'],
         "ret": 'idx of answer',
         "summary": "患者%s天前在%s情况下出现头痛"
         },
        {"idx": 3,
         "type": "choice",
         "question": "请问头痛符合以下哪种描述？",
         "answer": ['胀痛 （ 头部出现膨胀感并伴随疼痛 ）', '钝痛 （ 头部出现程度较剧烈但不尖锐的疼痛 ）',
                    '隐痛 （ 头部出现隐隐约约的疼痛 ）', '刺痛 （ 头部出现细针刺皮肤一样的疼痛 ）',
                    '闷痛 （ 头部出现被压迫一样的疼痛 ）'],
         "ret": 'idx of answer',
         "summary": "头痛呈%s"
         },
        {"idx": 4,
         "type": "choice",
         "question": "请问头痛符合以下哪种描述？",
         "answer": ["每次持续约数小时至数天",
                    "每次持续数分钟",
                    "每次持续数小时",
                    "每次持续数十秒", ],
         "ret": 'idx of answer',
         "summary": "%s"
         },
        {"idx": 5,
         "type": "choice",
         "question": "请问头痛是否安静休息后可好转?",
         "answer": ["是",
                    "否"],
         "ret": 'bool',
         "summary": "头痛安静休息后%s好转"
         },
        {"idx": 6,
         "type": "choice",
         "question": "请问什么情况下头痛加重?",
         "answer": ["活动",
                    "夜间",
                    "平躺",
                    "白天",
                    "低头",
                    "劳累", ],
         "ret": 'idx of answer',
         "summary": "在%s头痛加重"
         },
        {"idx": 7,
         "type": "choice",
         "question": "是否影响睡眠？",
         "answer": ["是",
                    "否", ],
         "ret": 'bool',
         "summary": "%s影响睡眠"
         },
        {"idx": 8,
         "type": "choice",
         "question": "请问头痛主要发生在什么部位？",
         "answer": [
             "头顶部",
             "双侧额颞部",
             "额部",
             "左侧额颞部",
             "右侧额颞部",
             "双侧颞部",
             "全头部",
         ],
         "ret": 'idx of answer',
         "summary": "部位位于%s"
         },
        {"idx": 9,
         "type": "choice",
         "question": "请问头痛以哪侧为主?",
         "answer": [
             "左侧",
             "右侧",
         ],
         "ret": 'idx of answer',
         "summary": "头痛以%s为主"
         },
        {"idx": 10,
         "type": "choice",
         "question": "请问是否伴有以下症状?",
         "answer": [
             "头晕",
             "呕吐 ",
             "恶心 ",
             "乏力 （ 感到没有力气 ） ",
             "发热 ",
             "都没有",
         ],
         "ret": 'idx of answer',
         "summary": "伴"
         },
        {"idx": 11,
         "type": "choice",
         "question": "请问您有以下哪种病史?",
         "classify": '既往史',
         "answer": [
             "高血压史",
             "心肌梗死病史",
             "糖尿病史",
             "外伤史",
             "急性肾炎病史",
             "都没有",
             "不明"
         ],
         "ret": 'idx of answer',
         "summary": "既往史： %s"
         },
        {"idx": 12,
         "type": "input",
         "classify": '过敏史',
         "question": "请问是否有过敏史(花粉/螨虫/粉尘/动物)?",
         "answer": [
         ],
         "ret": 'idx of answer',
         "summary": "过敏史： 对%s过敏"
         },

    ],
    "发烧": [
        {"idx": 1,
         "type": "input",
         "question": "请选择以下症状出现的时长",
         "answer": "__天",
         "ret": 'int',
         "summary": "发烧%s天"
         },
        {"idx": 2,
         "type": "choice",
         "question": "请问以下哪种情况下出现发热",
         "answer": ["劳累",
                    "受凉",
                    "感冒",
                    "打农药",
                    "暴晒",
                    "不明原因"],
         "ret": 'idx of answer',
         "summary": "患者%s天前在%s情况下出现发热"
         },
        {"idx": 3,
         "type": "input",
         "question": "请问您最高体温达多少度?",
         "answer": '39/不详',
         "ret": 'idx of answer',
         "summary": "最高体温: %s"
         },
        {"idx": 4,
         "type": "choice",
         "question": "请问什么情况下发热加重?",
         "answer": ["夜间",
                    "下午及晚上",
                    "午后",
                    "都没有"],
         "ret": 'idx of answer',
         "summary": "在%s发热严重"
         },
        {"idx": 5,
         "type": "choice",
         "question": "请问发热符合以下哪种描述？",
         "answer": [
             "阵发性 （ 症状多次发生，且每次自行缓解 ）",
             "持续性 （ 症状一直持续 ） "

         ],
         "ret": 'bool',
         "summary": "%s"
         },
        {"idx": 6,
         "type": "choice",
         "question": "请问是否伴有以下症状?",
         "answer": [
             "咳嗽",
             "咳痰 ",
             "咽痛 ",
             "畏寒 （ 害怕寒冷 ） ",
             "头痛 ",
             "都没有",
         ],
         "ret": 'idx of answer',
         "summary": "伴"
         },
        {"idx": 7,
         "type": "choice",
         "question": "请问您有以下哪种病史?",
         "classify": '既往史',
         "answer": [
             "高血压史",
             "心肌梗死病史",
             "糖尿病史",
             "外伤史",
             "急性肾炎病史",
             "都没有",
             "不明"
         ],
         "ret": 'idx of answer',
         "summary": "既往史： %s"
         },
        {"idx": 6,
         "type": "input",
         "classify": '过敏史',
         "question": "请问是否有过敏史(花粉/螨虫/粉尘/动物)?",
         "answer": [
         ],
         "ret": 'idx of answer',
         "summary": "过敏史： 对%s过敏"
         },

    ],
    "发热": [
        {"idx": 1,
         "type": "input",
         "question": "请选择以下症状出现的时长",
         "answer": "__天",
         "ret": 'int',
         "summary": "发烧%s天"
         },
        {"idx": 2,
         "type": "choice",
         "question": "请问以下哪种情况下出现发热",
         "answer": ["劳累",
                    "受凉",
                    "感冒",
                    "打农药",
                    "暴晒",
                    "不明原因"],
         "ret": 'idx of answer',
         "summary": "患者%s天前在%s情况下出现发热"
         },
        {"idx": 3,
         "type": "input",
         "question": "请问您最高体温达多少度?",
         "answer": '39/不详',
         "ret": 'idx of answer',
         "summary": "最高体温: %s"
         },
        {"idx": 4,
         "type": "choice",
         "question": "请问什么情况下发热加重?",
         "answer": ["夜间",
                    "下午及晚上",
                    "午后",
                    "都没有"],
         "ret": 'idx of answer',
         "summary": "在%s发热严重"
         },
        {"idx": 5,
         "type": "choice",
         "question": "请问发热符合以下哪种描述？",
         "answer": [
             "阵发性 （ 症状多次发生，且每次自行缓解 ）",
             "持续性 （ 症状一直持续 ） "

         ],
         "ret": 'bool',
         "summary": "%s"
         },
        {"idx": 6,
         "type": "choice",
         "question": "请问是否伴有以下症状?",
         "answer": [
             "咳嗽",
             "咳痰 ",
             "咽痛 ",
             "畏寒 （ 害怕寒冷 ） ",
             "头痛 ",
             "都没有",
         ],
         "ret": 'idx of answer',
         "summary": "伴"
         },
        {"idx": 7,
         "type": "choice",
         "question": "请问您有以下哪种病史?",
         "classify": '既往史',
         "answer": [
             "高血压史",
             "心肌梗死病史",
             "糖尿病史",
             "外伤史",
             "急性肾炎病史",
             "都没有",
             "不明"
         ],
         "ret": 'idx of answer',
         "summary": "既往史： %s"
         },
        {"idx": 6,
         "type": "input",
         "classify": '过敏史',
         "question": "请问是否有过敏史(花粉/螨虫/粉尘/动物)?",
         "answer": [
         ],
         "ret": 'idx of answer',
         "summary": "过敏史： 对%s过敏"
         },

    ],
    "高烧": [
        {"idx": 1,
         "type": "input",
         "question": "请选择以下症状出现的时长",
         "answer": "__天",
         "ret": 'int',
         "summary": "发烧%s天"
         },
        {"idx": 2,
         "type": "choice",
         "question": "请问以下哪种情况下出现发热",
         "answer": ["劳累",
                    "受凉",
                    "感冒",
                    "打农药",
                    "暴晒",
                    "不明原因"],
         "ret": 'idx of answer',
         "summary": "患者%s天前在%s情况下出现发热"
         },
        {"idx": 3,
         "type": "input",
         "question": "请问您最高体温达多少度?",
         "answer": '39/不详',
         "ret": 'idx of answer',
         "summary": "最高体温: %s"
         },
        {"idx": 4,
         "type": "choice",
         "question": "请问什么情况下发热加重?",
         "answer": ["夜间",
                    "下午及晚上",
                    "午后",
                    "都没有"],
         "ret": 'idx of answer',
         "summary": "在%s发热严重"
         },
        {"idx": 5,
         "type": "choice",
         "question": "请问发热符合以下哪种描述？",
         "answer": [
             "阵发性 （ 症状多次发生，且每次自行缓解 ）",
             "持续性 （ 症状一直持续 ） "

         ],
         "ret": 'bool',
         "summary": "%s"
         },
        {"idx": 6,
         "type": "choice",
         "question": "请问是否伴有以下症状?",
         "answer": [
             "咳嗽",
             "咳痰 ",
             "咽痛 ",
             "畏寒 （ 害怕寒冷 ） ",
             "头痛 ",
             "都没有",
         ],
         "ret": 'idx of answer',
         "summary": "伴"
         },
        {"idx": 7,
         "type": "choice",
         "question": "请问您有以下哪种病史?",
         "classify": '既往史',
         "answer": [
             "高血压史",
             "心肌梗死病史",
             "糖尿病史",
             "外伤史",
             "急性肾炎病史",
             "都没有",
             "不明"
         ],
         "ret": 'idx of answer',
         "summary": "既往史： %s"
         },
        {"idx": 6,
         "type": "input",
         "classify": '过敏史',
         "question": "请问是否有过敏史(花粉/螨虫/粉尘/动物)?",
         "answer": [
         ],
         "ret": 'idx of answer',
         "summary": "过敏史： 对%s过敏"
         },

    ],
}

export default fakeData;
